name = "Hermit-V2"
license = "MIT"
licenselink = "https://github.com/stepanpelc/hermit-V2/blob/main/LICENSE"
description = "Continuing Hermit's legacy to be minimal and fast theme"
homepage = "https://github.com/stepanpelc/hermit-V2"
demosite = "https://stepanpelc.github.io/hermit-V2/"
tags = ["blog", "minimal", "dark", "responsive", "landing", "dark mode"]
features = [
  "single column",
  "featured image",
  "social icons",
  "google analytics",
  "disqus",
  "customizable"
]

[module]
  [module.hugoVersion]
    extended = true
    min = '0.140.0'


[author]
  name = "BLZR"
  homepage = "https://blzr.sbs"
[original]
  name = "1bl4z3r"
  repo = "https://github.com/1bl4z3r/hermitv2"
